# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b6b350fa86065e174301363d871eaa97940d132414bcf8d87f6da256b7e53dfb575d23f43b8bef96b0c0ea70eefa4595117c0f6c2c8241853ebdd7810cf56ff
  aws_secret_key: hjhkjhjklhjlhl
  
test:
  secret_key_base: 607d5c63bef93718617f0d225cb5542842515505969b1977fa4ccf9b4eadf3152cc4e2ca29274df2ffd4755c545297cee81f1f35e1e30f7981b796641023d670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
